### ISSUE TITLE
code for NLQ fusion

### ISSUE THREAD

**Issue by a736120** [OpenGVLab/ego4d-eccv2022-solutions#10]
Hi,

Thank you for releasing the features. I was unable to find the code to fuse the features. I'm interested in reproducing the results of the paper on the NLQ dataset. Can you share these codes? 
![image](https://github.com/OpenGVLab/ego4d-eccv2022-solutions/assets/70309150/419093dc-f923-45bd-a9bc-bc1d455a1e64)

**Comment by cg1177** [comment]
Hello, this fusion method is to concatenate all features along channel dimension and modify the input channels of the first projector.
