### ISSUE TITLE
Question about the provided video feature for MQ and NLQ

### ISSUE THREAD

**Issue by yingsen1** [OpenGVLab/ego4d-eccv2022-solutions#11]
Thanks a lot for your nice work and providing your video feature.
I have a question about the provided feature. 
<img width="568" alt="image" src="https://github.com/OpenGVLab/ego4d-eccv2022-solutions/assets/20365909/93a4ad6c-80cc-4065-958c-d3aaa07aa318">
"The video features extracted by VideoMAE-L pretrained on verb and noun subset. ". Does it means that the features are used for the experiment "K700 → Verb" in the paper.

**Comment by cg1177** [comment]
Yes.
