### ISSUE TITLE
Validation data for SCOD

### ISSUE THREAD

**Issue by Davidyao99** [OpenGVLab/ego4d-eccv2022-solutions#2]
May I know what data format and which directories should I be placing my validation set to run the SCOD benchmark? Thank you!!

**Comment by cg1177** [comment]
We use mmdetection codebase, you can refer to its documents.

**Comment by Davidyao99** [comment]
I see, thanks!

**Comment by bryanzhou008** [comment]
@Davidyao99 I am having the same question, did you find related answers/information anywhere? Thank you very much!

**Comment by cg1177** [comment]
> @Davidyao99 I am having the same question, did you find related answers/information anywhere? Thank you very much!

We forgot to upload the converted annotation files in coco format; please give us a few days.

**Comment by bryanzhou008** [comment]
> > @Davidyao99 I am having the same question, did you find related answers/information anywhere? Thank you very much!
> 
> We forgot to upload the converted annotation files in coco format; please give us a few days.

Got it, thank you very much!
