### ISSUE TITLE
SCOD How to visualize bounding boxes of model?

### ISSUE THREAD

**Issue by Davidyao99** [OpenGVLab/ego4d-eccv2022-solutions#3]
I am running the evaluation code for the SCOD task and I downloaded the outputs to a pickle file. Looking at the output of the mode, it seems to be returning an array of size 100x5 for each validation image. I am a little confused as to how to translate this output to actual bounding boxes... Any advice on how I can do this? Thank you!!

**Comment by cg1177** [comment]
Our code is based on mmdetection. The codebase has the codes for visualizing bounding boxes.
