### ISSUE TITLE
Would you release the leading model and code for SCOD with Swin-L and Pre-trained on ImageNet-22K + Objects365

### ISSUE THREAD

**Issue by bryanzhou008** [OpenGVLab/ego4d-eccv2022-solutions#4]
Thanks!

**Comment by bryanzhou008** [comment]
Thank you very much, look forward to your release!

**Comment by bryanzhou008** [comment]
Hi there, any updates to the model release? Thanks in advance!

**Comment by czczup** [comment]
> Hi there @cg1177, any updates to the model release? Thanks in advance!

I will upload these model today.

**Comment by bryanzhou008** [comment]
> > Hi there @cg1177, any updates to the model release? Thanks in advance!
> 
> I will upload this model today.

Thanks a lot!

**Comment by bryanzhou008** [comment]
A quick follow-up question: could you state the per GPU memory required by the training script (or just the per GPU memory used in this work)? Thanks again!
