### ISSUE TITLE
Access to the FHP checkpoints

### ISSUE THREAD

**Issue by kurshakuz** [OpenGVLab/ego4d-eccv2022-solutions#5]
In the readme it is mentioned that the code and checkpoints of pretraining for the FHP task are released, can you please guide me where can I find those?

**Comment by cg1177** [comment]
Hello. We did not release the FHP checkpoints before. 
We just released the last checkpoint at [https://github.com/OpenGVLab/ego4d-eccv2022-solutions/releases/tag/1.0.0]() since we now do not have GPU to test which checkpoint is the best.

**Comment by kurshakuz** [comment]
Sure, that's good enough!

**Comment by kurshakuz** [comment]
Hi @cg1177! I wanted also to ask one more question. In the https://github.com/opengvlab/ego4d-eccv2022-solutions#training-2 you mention that `the weights pretrained on Ego4D verb subset`. Are referring to that particular model here: https://github.com/OpenGVLab/ego4d-eccv2022-solutions/releases/download/1.0.0/ego4d_verb_uniformer_base_16x320_k600_ep9.pt ?
I want to replicate your experiments and would like to know if I am following the steps correctly. Thanks!

**Comment by takfate** [comment]
> Hi @cg1177! I wanted also to ask one more question. In the https://github.com/opengvlab/ego4d-eccv2022-solutions#training-2 you mention that `the weights pretrained on Ego4D verb subset`. Are referring to that particular model here: https://github.com/OpenGVLab/ego4d-eccv2022-solutions/releases/download/1.0.0/ego4d_verb_uniformer_base_16x320_k600_ep9.pt ? I want to replicate your experiments and would like to know if I am following the steps correctly. Thanks!

Yes.

**Comment by cg1177** [comment]
> Hi @cg1177! I wanted also to ask one more question. In the https://github.com/opengvlab/ego4d-eccv2022-solutions#training-2 you mention that `the weights pretrained on Ego4D verb subset`. Are referring to that particular model here: https://github.com/OpenGVLab/ego4d-eccv2022-solutions/releases/download/1.0.0/ego4d_verb_uniformer_base_16x320_k600_ep9.pt ? I want to replicate your experiments and would like to know if I am following the steps correctly. Thanks!

yes.
