### ISSUE TITLE
How to modify number of temporal views for the FHP task

### ISSUE THREAD

**Issue by kurshakuz** [OpenGVLab/ego4d-eccv2022-solutions#8]
Hi!

I am curious to know, what parameters are needed to be modified to change the number of temporal views (V) as defined in your experiments? Do you also use the same number of frames (T) both during training and testing stages?

![image](https://github.com/OpenGVLab/ego4d-eccv2022-solutions/assets/28868430/c402f45f-550e-4227-bc46-eba5157bb110)

Thanks!

**Comment by cg1177** [comment]
Hello, does modifying parameter `test_num_segments` work?
It's been quite some time, but I remember it was effective.

**Comment by kurshakuz** [comment]
Yes, it worked, thanks!
