### ISSUE TITLE
STA pretrained model checkpoint

### ISSUE THREAD

**Issue by kim-sanghwan** [OpenGVLab/ego4d-eccv2022-solutions#9]
Interesting works! I would like to cite your work regarding STA task but I couldn't find pretrained model for STA. 
Can you release the pretrained checkpoint (ViT-L) for STA?
It should be the model corresponding to "/mnt/petrelfs/share_data/chenguo/ego_forecasting/pretrained_models/vitl_v.pt"
at https://github.com/OpenGVLab/ego4d-eccv2022-solutions/blob/main/forecasting_eval/configs/Ego4dShortTermAnticipation/VIT3D.yaml#L5

Thank you in advance!

**Comment by cg1177** [comment]
Hello, this checkpoint is [ego4d_verb_pretrain_vitl_k700.pt](https://github.com/OpenGVLab/ego4d-eccv2022-solutions/releases/download/1.0.0/ego4d_verb_pretrain_vitl_k700.pt)
